// LOCALHOST 
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/6443a821cf8de0cf1bba6dbe
### 
GET http://localhost:8080/contacts/6443a83dcf8de0cf1bba6dbf
### 
GET http://localhost:8080/contacts/6443a84fcf8de0cf1bba6dc0

// PRODUCTION Deploy 
### 
GET https://cse341-instructor.herokuapp.com/contacts 
###
GET https://cse341-spring2023.onrender.com/contacts
### 
GET https://cse341-instructor.herokuapp.com/contacts/6443a821cf8de0cf1bba6dbe
### 
GET https://cse341-instructor.herokuapp.com/contacts/6443a83dcf8de0cf1bba6dbf
### 
GET https://cse341-instructor.herokuapp.com/contacts/6443a84fcf8de0cf1bba6dc0
